### Exploring Staple Food Price Dataset

In [1]:
import pandas as pd
# Load the dataset
df = pd.read_csv('data/raw/ethiopian_agriculture/02_staple_food_price.csv')
df.head()

,country,market,admin_1,longitude,latitude,cpcv2,product,source_document,period_date,price_type,product_source,unit,unit_type,currency,value,Unnamed: 15
0,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,R01701BD,Beans (Haricot),Famine Early Warning Systems Network (FEWS NET...,2020-01-01,Retail,Local,kg,Weight,ETB,41.0,NaN
1,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,R01701BD,Beans (Haricot),Famine Early Warning Systems Network (FEWS NET...,2020-01-08,Retail,Local,kg,Weight,ETB,46.0,NaN
2,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,R01701BD,Beans (Haricot),Famine Early Warning Systems Network (FEWS NET...,2020-01-15,Retail,Local,kg,Weight,ETB,48.6,NaN
3,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,R01701BD,Beans (Haricot),Famine Early Warning Systems Network (FEWS NET...,2020-01-22,Retail,Local,kg,Weight,ETB,49.0,NaN
4,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,R01701BD,Beans (Haricot),Famine Early Warning Systems Network (FEWS NET...,2020-01-29,Retail,Local,kg,Weight,ETB,50.0,NaN

In [2]:
df.tail()

,country,market,admin_1,longitude,latitude,cpcv2,product,source_document,period_date,price_type,product_source,unit,unit_type,currency,value,Unnamed: 15
77012,Ethiopia,Yabelo,Oromia,38.0934,4.89343,R01112AA,Wheat Grain,Famine Early Warning Systems Network (FEWS NET...,2023-05-24,Retail,Local,kg,Weight,ETB,61.482,NaN
77013,Ethiopia,Yabelo,Oromia,38.0934,4.89343,R01112AA,Wheat Grain,Famine Early Warning Systems Network (FEWS NET...,2023-05-31,Retail,Local,kg,Weight,ETB,62.310,NaN
77014,Ethiopia,Yabelo,Oromia,38.0934,4.89343,R01112AA,Wheat Grain,Famine Early Warning Systems Network (FEWS NET...,2023-06-07,Retail,Local,kg,Weight,ETB,58.368,NaN
77015,Ethiopia,Yabelo,Oromia,38.0934,4.89343,R01112AA,Wheat Grain,Famine Early Warning Systems Network (FEWS NET...,2023-06-14,Retail,Local,kg,Weight,ETB,57.138,NaN
77016,Ethiopia,Yabelo,Oromia,38.0934,4.89343,R01112AA,Wheat Grain,Famine Early Warning Systems Network (FEWS NET...,2023-06-21,Retail,Local,kg,Weight,ETB,51.930,NaN

In [4]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Shape: (77017, 16)

Columns:
['country', 'market', 'admin_1', 'longitude', 'latitude', 'cpcv2', 'product', 'source_document', 'period_date', 'price_type', 'product_source', 'unit', 'unit_type', 'currency', 'value', 'Unnamed: 15']

Data Types:
country                str
market                 str
admin_1                str
longitude          float64
latitude           float64
cpcv2                  str
product                str
source_document        str
period_date            str
price_type             str
product_source         str
unit                   str
unit_type              str
currency               str
value              float64
Unnamed: 15        float64
dtype: object

Missing Values:
country                0
market                 0
admin_1                0
longitude              0
latitude               0
cpcv2                  0
product                0
source_document        0
period_date            0
price_type             0
product_source         0
unit                   0
unit_type              0
currency               0
value              20645
Unnamed: 15        77017
dtype: int64

Duplicate Rows:
0

In [5]:
df = df.drop(columns=["Unnamed: 15"])

In [7]:
missing_price = df[df["value"].isna()]

print("Rows with missing price:", len(missing_price))

display(missing_price.head())

Rows with missing price: 20645

,country,market,admin_1,longitude,latitude,cpcv2,product,source_document,period_date,price_type,product_source,unit,unit_type,currency,value
182,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,L02121AB,Camels (Local Quality),Famine Early Warning Systems Network (FEWS NET...,2020-01-01,Retail,Local,ea,Item,ETB,NaN
183,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,L02121AB,Camels (Local Quality),Famine Early Warning Systems Network (FEWS NET...,2020-01-08,Retail,Local,ea,Item,ETB,NaN
184,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,L02121AB,Camels (Local Quality),Famine Early Warning Systems Network (FEWS NET...,2020-01-15,Retail,Local,ea,Item,ETB,NaN
185,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,L02121AB,Camels (Local Quality),Famine Early Warning Systems Network (FEWS NET...,2020-01-22,Retail,Local,ea,Item,ETB,NaN
186,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,L02121AB,Camels (Local Quality),Famine Early Warning Systems Network (FEWS NET...,2020-01-29,Retail,Local,ea,Item,ETB,NaN

In [8]:
print("Missing prices by product:")
print(missing_price["product"].value_counts().head(20))

print("\nMissing prices by market:")
print(missing_price["market"].value_counts().head(20))

print("\nMissing prices by price type:")
print(missing_price["price_type"].value_counts())

print("\nMissing prices by product source:")
print(missing_price["product_source"].value_counts())

Missing prices by product:
product
Camels (Local Quality)                           2779
Sorghum (Yellow)                                 2662
Wheat Flour                                      2089
Beans (Haricot)                                  1338
Sorghum (White)                                  1174
Oxen (Local Quality)                             1100
Mixed Teff                                       1085
Horse beans                                      1064
Sorghum (Red)                                    1010
Firewood                                          742
Rice (Milled)                                     673
Maize Grain (White)                               609
Gasoline                                          608
Wheat Grain                                       597
Refined sugar                                     578
Goats (Local Quality)                             515
Diesel                                            509
Sheep (Local Quality)                             507
Refined Vegetable Oil                             506
Casual Labor (unskilled, daily, without food)     500
Name: count, dtype: int64

Missing prices by market:
market
Mekele               2737
Shire                2588
Awash                1987
Sekota               1317
Dire Dawa, Kezira    1263
Logia                 996
Beddenno              860
Gambella              841
Nekemte               793
Sodo                  770
Dessie                752
Sikela                721
Jinka                 719
Degehabour            674
Bahir Dar             665
Warder                653
Shashemene            501
Chereti               434
Gode                  420
Nazareth, Adama       392
Name: count, dtype: int64

Missing prices by price type:
price_type
Retail    20145
Wage        500
Name: count, dtype: int64

Missing prices by product source:
product_source
Local     17771
Import     2874
Name: count, dtype: int64